Repository jenkinsci/mock-load-builder-plugin, pull requests merged in 2023-01, with the labels that each got.

#51 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#78 Bump baseline, POM, BOM, etc.
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/release-drafter.yaml
  Jenkinsfile
  pom.xml
  src/main/resources/index.jelly
Labels: dependencies

#80 Created `withMockLoad` step
  src/main/java/jenkins/plugin/mockloadbuilder/PipelineMockProjectFactory.java
  src/main/java/jenkins/plugin/mockloadbuilder/WithMockLoadStep.java
  src/main/resources/jenkins/plugin/mockloadbuilder/WithMockLoadStep/config.jelly
  src/main/resources/jenkins/plugin/mockloadbuilder/WithMockLoadStep/config.properties
  src/main/resources/jenkins/plugin/mockloadbuilder/WithMockLoadStep/help-averageDuration.html
  src/main/resources/jenkins/plugin/mockloadbuilder/WithMockLoadStep/help.html
  src/test/java/jenkins/plugin/mockloadbuilder/WithMockLoadStepTest.java
Labels: enhancement
